<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Artha.Core\Artha.Core.csproj" />
    <ProjectReference Include="..\Artha.Infrastructure\Artha.Infrastructure.csproj" />
  </ItemGroup>

</Project>
