import { addIcons } from 'ionicons';
import {
  add,
  addCircle,
  arrowDown,
  arrowUp,
  calendar,
  calendarOutline,
  card,
  cardOutline,
  chevronBack,
  chevronForward,
  closeOutline,
  ellipsisHorizontal,
  home,
  homeOutline,
  layers,
  listOutline,
  logOutOutline,
  pencil,
  pieChartOutline,
  pricetag,
  pricetagOutline,
  receiptOutline,
  saveOutline,
  settings,
  settingsOutline,
  statsChart,
  statsChartOutline,
  todayOutline,
  trash,
  trendingDown,
  trendingUp,
  wallet,
  walletOutline,
} from 'ionicons/icons';

export function registerIcons(): void {
  addIcons({
    add,
    'add-circle': addCircle,
    'arrow-down': arrowDown,
    'arrow-up': arrowUp,
    calendar,
    'calendar-outline': calendarOutline,
    card,
    'card-outline': cardOutline,
    'chevron-back': chevronBack,
    'chevron-forward': chevronForward,
    'close-outline': closeOutline,
    'ellipsis-horizontal': ellipsisHorizontal,
    home,
    'home-outline': homeOutline,
    layers,
    'list-outline': listOutline,
    'log-out-outline': logOutOutline,
    pencil,
    'pie-chart-outline': pieChartOutline,
    pricetag,
    'pricetag-outline': pricetagOutline,
    'receipt-outline': receiptOutline,
    'save-outline': saveOutline,
    settings,
    'settings-outline': settingsOutline,
    'stats-chart': statsChart,
    'stats-chart-outline': statsChartOutline,
    'today-outline': todayOutline,
    trash,
    'trending-down': trendingDown,
    'trending-up': trendingUp,
    wallet,
    'wallet-outline': walletOutline,
  });
}
