import { addIcons } from 'ionicons';
import {
  add,
  addCircle,
  airplane,
  arrowDown,
  arrowUp,
  bagHandle,
  basket,
  book,
  build,
  bus,
  cafe,
  calendarOutline,
  car,
  card,
  cardOutline,
  cart,
  cash,
  chevronBack,
  chevronForward,
  cloudUploadOutline,
  closeOutline,
  ellipsisHorizontal,
  fastFood,
  film,
  fitness,
  flash,
  gameController,
  gift,
  heart,
  home,
  homeOutline,
  layers,
  leaf,
  listOutline,
  logOutOutline,
  medkit,
  musicalNotes,
  paw,
  pencil,
  phonePortrait,
  pieChartOutline,
  pricetag,
  pricetagOutline,
  receipt,
  receiptOutline,
  restaurant,
  saveOutline,
  school,
  settings,
  settingsOutline,
  shirt,
  statsChart,
  statsChartOutline,
  todayOutline,
  train,
  trash,
  trendingDown,
  trendingUp,
  tv,
  umbrella,
  wallet,
  walletOutline,
  water,
  wifi,
} from 'ionicons/icons';

export function registerIcons(): void {
  addIcons({
    add,
    'add-circle': addCircle,
    'arrow-down': arrowDown,
    'arrow-up': arrowUp,
    'calendar-outline': calendarOutline,
    card,
    'card-outline': cardOutline,
    'chevron-back': chevronBack,
    'chevron-forward': chevronForward,
    'cloud-upload-outline': cloudUploadOutline,
    'close-outline': closeOutline,
    'ellipsis-horizontal': ellipsisHorizontal,
    home,
    'home-outline': homeOutline,
    layers,
    'list-outline': listOutline,
    'log-out-outline': logOutOutline,
    pencil,
    'pie-chart-outline': pieChartOutline,
    pricetag,
    'pricetag-outline': pricetagOutline,
    'receipt-outline': receiptOutline,
    'save-outline': saveOutline,
    settings,
    'settings-outline': settingsOutline,
    'stats-chart': statsChart,
    'stats-chart-outline': statsChartOutline,
    'today-outline': todayOutline,
    trash,
    'trending-down': trendingDown,
    'trending-up': trendingUp,
    wallet,
    'wallet-outline': walletOutline,
    // Category picker icons.
    airplane,
    'bag-handle': bagHandle,
    basket,
    book,
    build,
    bus,
    cafe,
    car,
    cart,
    cash,
    'fast-food': fastFood,
    film,
    fitness,
    flash,
    'game-controller': gameController,
    gift,
    heart,
    leaf,
    medkit,
    'musical-notes': musicalNotes,
    paw,
    'phone-portrait': phonePortrait,
    receipt,
    restaurant,
    school,
    shirt,
    train,
    tv,
    umbrella,
    water,
    wifi,
  });
}
